# Generated by Django 4.2.11 on 2026-06-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('finance', '财务'), ('coach', '教练'), ('student', '学员')], default='admin', max_length=20, verbose_name='角色'),
        ),
    ]
