# Generated by Django 4.2.11 on 2026-06-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='套餐编码')),
                ('type', models.CharField(choices=[('normal', '普通班'), ('premium', '精品班'), ('vip', 'VIP班')], max_length=20, verbose_name='套餐类型')),
                ('license_type', models.CharField(choices=[('C1', 'C1证'), ('C2', 'C2证'), ('D', 'D证'), ('all', '通用')], default='all', max_length=10, verbose_name='适用驾照类型')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基准报名费')),
                ('total_hours', models.IntegerField(default=0, verbose_name='包含课时')),
                ('description', models.TextField(blank=True, null=True, verbose_name='套餐描述')),
                ('payment_type', models.CharField(choices=[('full', '一次性付款'), ('installment', '分期付款'), ('both', '支持两种')], default='both', max_length=20, verbose_name='付款方式')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='分期首付')),
                ('installment_months', models.IntegerField(default=0, verbose_name='分期期数')),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='每期金额')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报名套餐',
                'verbose_name_plural': '报名套餐',
                'db_table': 'packages',
                'ordering': ['-id'],
            },
        ),
    ]
