# Generated by Django 4.2.11 on 2026-06-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已约考'), ('absent', '缺考'), ('passed', '考试通过'), ('failed', '考试未通过'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('booking_type', models.CharField(choices=[('admin', '管理员代约'), ('self', '自主约考')], default='admin', max_length=20, verbose_name='预约类型')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='考试分数')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='预约时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '约考记录',
                'verbose_name_plural': '约考记录',
                'db_table': 'exam_bookings',
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考场名称')),
                ('address', models.CharField(max_length=200, verbose_name='考场地址')),
                ('capacity', models.IntegerField(default=50, verbose_name='容纳人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考场',
                'verbose_name_plural': '考场',
                'db_table': 'exam_rooms',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, '科目一（理论）'), (2, '科目二（场地）'), (3, '科目三（道路）'), (4, '科目四（安全文明）')], verbose_name='考试科目')),
                ('exam_date', models.DateField(verbose_name='考试日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('total_quota', models.IntegerField(default=50, verbose_name='总名额')),
                ('booked_quota', models.IntegerField(default=0, verbose_name='已预约')),
                ('status', models.CharField(choices=[('open', '预约开放'), ('locked', '预约关闭'), ('completed', '考试完成'), ('cancelled', '已取消')], default='open', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.examroom', verbose_name='考场')),
            ],
            options={
                'verbose_name': '考试安排',
                'verbose_name_plural': '考试安排',
                'db_table': 'exam_schedules',
                'ordering': ['-exam_date', '-start_time'],
            },
        ),
    ]
