# Generated by Django 4.2.11 on 2026-06-06 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_installmentscheme_installmentplan_total_late_fee_and_more'),
        ('students', '0004_student_last_hours_reminder_student_practical_hours_and_more'),
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, '科目一（理论）'), (2, '科目二（场地）'), (3, '科目三（道路）'), (4, '科目四（安全文明）')], unique=True, verbose_name='考试科目')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='补考费金额')),
                ('description', models.TextField(blank=True, null=True, verbose_name='费用说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '补考费规则',
                'verbose_name_plural': '补考费规则',
                'db_table': 'exam_fee_rules',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='ExamFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, '科目一（理论）'), (2, '科目二（场地）'), (3, '科目三（道路）'), (4, '科目四（安全文明）')], verbose_name='考试科目')),
                ('fee_type', models.CharField(choices=[('absent', '缺考'), ('failed', '考试未通过')], max_length=20, verbose_name='费用类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='费用金额')),
                ('status', models.CharField(choices=[('unpaid', '待缴费'), ('paid', '已缴费'), ('cancelled', '已取消')], default='unpaid', max_length=20, verbose_name='状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='缴费时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_fees', to='exams.exambooking', verbose_name='关联约考记录')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_fees', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_fee', to='payments.payment', verbose_name='关联缴费')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_fees', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '补考账单',
                'verbose_name_plural': '补考账单',
                'db_table': 'exam_fees',
                'ordering': ['-id'],
            },
        ),
    ]
