# Generated by Django 4.2.11 on 2026-06-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('license_type', models.CharField(choices=[('C1', 'C1证（手动挡）'), ('C2', 'C2证（自动挡）'), ('D', 'D证（摩托车）')], max_length=10, verbose_name='驾照类型')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='住址')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='students/id_cards/', verbose_name='身份证正面')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='students/id_cards/', verbose_name='身份证背面')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='学员照片')),
                ('status', models.CharField(choices=[('studying', '学习中'), ('graduated', '已毕业'), ('suspended', '已休学'), ('cancelled', '已取消')], default='studying', max_length=20, verbose_name='状态')),
                ('total_hours', models.IntegerField(default=0, verbose_name='总课时')),
                ('used_hours', models.IntegerField(default=0, verbose_name='已用课时')),
                ('enroll_date', models.DateField(auto_now_add=True, verbose_name='报名日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'db_table': 'students',
                'ordering': ['-id'],
            },
        ),
    ]
