# Generated by Django 4.2.11 on 2026-06-06 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_user_alter_student_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_hours_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次课时提醒时间'),
        ),
        migrations.AddField(
            model_name='student',
            name='practical_hours',
            field=models.IntegerField(default=0, verbose_name='实操总课时'),
        ),
        migrations.AddField(
            model_name='student',
            name='theory_hours',
            field=models.IntegerField(default=0, verbose_name='理论总课时'),
        ),
        migrations.AddField(
            model_name='student',
            name='used_practical_hours',
            field=models.IntegerField(default=0, verbose_name='已用实操课时'),
        ),
        migrations.AddField(
            model_name='student',
            name='used_theory_hours',
            field=models.IntegerField(default=0, verbose_name='已用理论课时'),
        ),
        migrations.CreateModel(
            name='HourRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_type', models.CharField(choices=[('theory', '理论课时'), ('practical', '实操课时')], max_length=20, verbose_name='课时类型')),
                ('operation_type', models.CharField(choices=[('consume', '核销'), ('add', '增加'), ('refund', '退还'), ('renewal', '续课')], max_length=20, verbose_name='操作类型')),
                ('hours', models.IntegerField(verbose_name='课时数量')),
                ('hours_before', models.IntegerField(verbose_name='操作前课时')),
                ('hours_after', models.IntegerField(verbose_name='操作后课时')),
                ('sign_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('sign_out_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hour_records', to=settings.AUTH_USER_MODEL, verbose_name='教练')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hour_records_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_records', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '课时核销记录',
                'verbose_name_plural': '课时核销记录',
                'db_table': 'hour_records',
                'ordering': ['-id'],
            },
        ),
    ]
