# Generated by Django 4.2.11 on 2026-06-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='分期总金额')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='首付金额')),
                ('months', models.IntegerField(verbose_name='分期期数')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每期金额')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已还金额')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='剩余金额')),
                ('status', models.CharField(choices=[('unpaid', '未还款'), ('paid', '已还款'), ('overdue', '已逾期')], default='unpaid', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分期计划',
                'verbose_name_plural': '分期计划',
                'db_table': 'installment_plans',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(verbose_name='期次')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='还款金额')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='实际还款日期')),
                ('status', models.CharField(choices=[('unpaid', '未还款'), ('paid', '已还款'), ('overdue', '已逾期')], default='unpaid', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分期还款记录',
                'verbose_name_plural': '分期还款记录',
                'db_table': 'installment_records',
                'ordering': ['plan', 'period'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('full', '一次性全款'), ('down', '首付'), ('installment', '分期还款')], max_length=20, verbose_name='缴费类型')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank', '银行转账'), ('card', '刷卡')], max_length=20, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='缴费金额')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应缴总金额')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='剩余未缴')),
                ('installment_no', models.IntegerField(default=0, verbose_name='分期期次')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='confirmed', max_length=20, verbose_name='状态')),
                ('receipt_no', models.CharField(max_length=50, unique=True, verbose_name='缴费凭证号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='缴费时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '缴费记录',
                'verbose_name_plural': '缴费记录',
                'db_table': 'payments',
                'ordering': ['-id'],
            },
        ),
    ]
