# Generated by Django 4.2.11 on 2026-06-06 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_student_last_hours_reminder_student_practical_hours_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='方案名称')),
                ('down_payment_ratio', models.DecimalField(decimal_places=2, help_text='如30表示首付30%', max_digits=5, verbose_name='首付比例(%)')),
                ('periods', models.IntegerField(help_text='如6表示分6期', verbose_name='分期期数')),
                ('due_day', models.IntegerField(help_text='如15表示每月15日还款', verbose_name='每期还款日')),
                ('late_fee_ratio', models.DecimalField(decimal_places=4, help_text='每日滞纳金比例，如0.05表示每日0.05%', max_digits=5, verbose_name='逾期滞纳金比例(%)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='方案描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分期方案',
                'verbose_name_plural': '分期方案',
                'db_table': 'installment_schemes',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='total_late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计滞纳金'),
        ),
        migrations.AddField(
            model_name='installmentrecord',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='滞纳金'),
        ),
        migrations.AddField(
            model_name='installmentrecord',
            name='late_fee_days',
            field=models.IntegerField(default=0, verbose_name='逾期天数'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full', '一次性全款'), ('down', '首付'), ('installment', '分期还款'), ('makeup_exam', '补考费'), ('course_renewal', '续课费')], max_length=20, verbose_name='缴费类型'),
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('phone', '电话'), ('sms', '短信'), ('wechat', '微信'), ('visit', '上门'), ('other', '其他')], max_length=20, verbose_name='催缴方式')),
                ('reminder_date', models.DateField(auto_now_add=True, verbose_name='催缴日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='催缴金额')),
                ('result', models.CharField(choices=[('promised', '承诺还款'), ('partial', '部分还款'), ('no_answer', '无人接听'), ('refused', '拒绝还款'), ('pending', '待跟进')], max_length=20, verbose_name='催缴结果')),
                ('promised_date', models.DateField(blank=True, null=True, verbose_name='承诺还款日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('installment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='payments.installmentplan', verbose_name='分期计划')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reminders', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '催缴记录',
                'verbose_name_plural': '催缴记录',
                'db_table': 'payment_reminders',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='payments.installmentscheme', verbose_name='分期方案'),
        ),
    ]
